'use client';

import { useState } from 'react';
import { useAuth } from '@/contexts/AuthContext';
import { fetchKPIData, fetchMembers, fetchSessions } from '@/lib/firestore';
import jsPDF from 'jspdf';

interface ReportGeneratorProps {
  isOpen: boolean;
  onClose: () => void;
}

export default function ReportGenerator({ isOpen, onClose }: ReportGeneratorProps) {
  const { gymId, gymName } = useAuth();
  const [isGenerating, setIsGenerating] = useState(false);
  const [reportType, setReportType] = useState<'monthly' | 'custom'>('monthly');

  const generateMonthlyReport = async () => {
    if (!gymId) return;

    setIsGenerating(true);
    try {
      // Fetch data
      const kpiData = await fetchKPIData(gymId);
      const members = await fetchMembers(gymId);
      const sessions = await fetchSessions(gymId, 100);

      // Create PDF
      const doc = new jsPDF();
      const pageWidth = doc.internal.pageSize.getWidth();
      let yPos = 20;

      // Title
      doc.setFontSize(20);
      doc.setFont('helvetica', 'bold');
      doc.text('Monthly Performance Report', pageWidth / 2, yPos, { align: 'center' });
      yPos += 15;

      // Gym Info
      doc.setFontSize(12);
      doc.setFont('helvetica', 'normal');
      doc.text(`Gym: ${gymName || 'N/A'}`, 20, yPos);
      yPos += 8;
      doc.text(`Report Date: ${new Date().toLocaleDateString('ja-JP')}`, 20, yPos);
      yPos += 15;

      // KPI Section
      doc.setFontSize(16);
      doc.setFont('helvetica', 'bold');
      doc.text('Key Performance Indicators', 20, yPos);
      yPos += 10;

      doc.setFontSize(12);
      doc.setFont('helvetica', 'normal');
      doc.text(`Total Members: ${kpiData.totalMembers}`, 30, yPos);
      yPos += 7;
      doc.text(`Active Members: ${kpiData.activeMembers}`, 30, yPos);
      yPos += 7;
      doc.text(`Dormant Members: ${kpiData.dormantMembers}`, 30, yPos);
      yPos += 7;
      doc.text(`New Members This Month: ${kpiData.newMembersThisMonth}`, 30, yPos);
      yPos += 7;
      doc.text(`Total Sessions: ${kpiData.totalSessions}`, 30, yPos);
      yPos += 7;
      doc.text(`Today's Sessions: ${kpiData.todaySessions}`, 30, yPos);
      yPos += 15;

      // Member Statistics
      doc.setFontSize(16);
      doc.setFont('helvetica', 'bold');
      doc.text('Member Statistics', 20, yPos);
      yPos += 10;

      doc.setFontSize(12);
      doc.setFont('helvetica', 'normal');
      
      // Contract type breakdown
      const contractTypes = {
        premium: members.filter(m => m.contractType === 'premium').length,
        standard: members.filter(m => m.contractType === 'standard').length,
        basic: members.filter(m => m.contractType === 'basic').length,
        trial: members.filter(m => m.contractType === 'trial').length,
      };

      doc.text(`Premium Members: ${contractTypes.premium}`, 30, yPos);
      yPos += 7;
      doc.text(`Standard Members: ${contractTypes.standard}`, 30, yPos);
      yPos += 7;
      doc.text(`Basic Members: ${contractTypes.basic}`, 30, yPos);
      yPos += 7;
      doc.text(`Trial Members: ${contractTypes.trial}`, 30, yPos);
      yPos += 15;

      // Session Statistics
      doc.setFontSize(16);
      doc.setFont('helvetica', 'bold');
      doc.text('Session Statistics', 20, yPos);
      yPos += 10;

      doc.setFontSize(12);
      doc.setFont('helvetica', 'normal');

      const sessionTypes = {
        personal: sessions.filter(s => s.type === 'personal').length,
        group: sessions.filter(s => s.type === 'group').length,
        trial: sessions.filter(s => s.type === 'trial').length,
        consultation: sessions.filter(s => s.type === 'consultation').length,
      };

      doc.text(`Personal Sessions: ${sessionTypes.personal}`, 30, yPos);
      yPos += 7;
      doc.text(`Group Sessions: ${sessionTypes.group}`, 30, yPos);
      yPos += 7;
      doc.text(`Trial Sessions: ${sessionTypes.trial}`, 30, yPos);
      yPos += 7;
      doc.text(`Consultation Sessions: ${sessionTypes.consultation}`, 30, yPos);
      yPos += 15;

      // Footer
      doc.setFontSize(10);
      doc.setFont('helvetica', 'italic');
      doc.text(
        'Generated by GYM MATCH Management System',
        pageWidth / 2,
        doc.internal.pageSize.getHeight() - 10,
        { align: 'center' }
      );

      // Save PDF
      const fileName = `gym-match-report-${new Date().toISOString().split('T')[0]}.pdf`;
      doc.save(fileName);

      console.log('✅ Report generated successfully:', fileName);
      onClose();
    } catch (error) {
      console.error('❌ Error generating report:', error);
      alert('レポート生成に失敗しました。もう一度お試しください。');
    } finally {
      setIsGenerating(false);
    }
  };

  const handleGenerate = () => {
    if (reportType === 'monthly') {
      generateMonthlyReport();
    }
  };

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
      <div className="bg-white rounded-xl shadow-2xl max-w-md w-full">
        {/* Header */}
        <div className="bg-gradient-to-r from-green-600 to-green-700 px-6 py-4 rounded-t-xl">
          <div className="flex items-center justify-between">
            <h2 className="text-xl font-bold text-white flex items-center">
              <svg className="w-6 h-6 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 17v-2m3 2v-4m3 4v-6m2 10H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
              </svg>
              レポート作成
            </h2>
            <button
              onClick={onClose}
              disabled={isGenerating}
              className="text-white hover:text-gray-200 transition disabled:opacity-50"
            >
              <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
              </svg>
            </button>
          </div>
        </div>

        {/* Body */}
        <div className="p-6">
          <div className="mb-6">
            <label className="block text-sm font-medium text-gray-900 mb-2">
              レポートタイプ
            </label>
            <select
              value={reportType}
              onChange={(e) => setReportType(e.target.value as any)}
              className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-green-500 focus:border-transparent text-gray-900"
              disabled={isGenerating}
            >
              <option value="monthly">月次レポート</option>
              <option value="custom" disabled>カスタムレポート（近日対応）</option>
            </select>
          </div>

          <div className="bg-blue-50 border border-blue-200 rounded-lg p-4 mb-6">
            <h3 className="font-medium text-blue-900 mb-2 flex items-center">
              <svg className="w-5 h-5 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
              </svg>
              レポート内容
            </h3>
            <ul className="text-sm text-blue-800 space-y-1">
              <li>• KPI指標（会員数、セッション数等）</li>
              <li>• 会員統計（契約タイプ別）</li>
              <li>• セッション統計（タイプ別）</li>
              <li>• PDF形式でダウンロード</li>
            </ul>
          </div>

          {/* Buttons */}
          <div className="flex space-x-3">
            <button
              onClick={onClose}
              disabled={isGenerating}
              className="flex-1 px-4 py-2 border border-gray-300 rounded-lg text-gray-900 hover:bg-gray-50 transition disabled:opacity-50"
            >
              キャンセル
            </button>
            <button
              onClick={handleGenerate}
              disabled={isGenerating}
              className="flex-1 px-4 py-2 bg-green-600 text-white rounded-lg hover:bg-green-700 transition disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center"
            >
              {isGenerating ? (
                <>
                  <svg className="animate-spin h-5 w-5 mr-2" fill="none" viewBox="0 0 24 24">
                    <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                    <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                  </svg>
                  生成中...
                </>
              ) : (
                <>
                  <svg className="w-5 h-5 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
                  </svg>
                  PDF生成
                </>
              )}
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
