/**
 * Invoice Generator for GYM MATCH Manager
 * 
 * Features:
 * - Generate professional invoices for payments
 * - Support for session payments and memberships
 * - Automatic numbering and date formatting
 * - Japanese-localized invoice format
 */

import jsPDF from 'jspdf';
import type { Payment } from '@/lib/payment';

export interface InvoiceData {
  invoiceNumber: string;
  issueDate: Date;
  dueDate: Date;
  gymName: string;
  gymAddress?: string;
  gymPhone?: string;
  customerName: string;
  customerEmail?: string;
  items: Array<{
    description: string;
    quantity: number;
    unitPrice: number;
    amount: number;
  }>;
  subtotal: number;
  tax: number;
  total: number;
  notes?: string;
}

/**
 * Generate invoice PDF from payment data
 */
export async function generateInvoicePDF(payment: Payment, gymInfo: any, filename?: string): Promise<Blob> {
  const doc = new jsPDF('p', 'mm', 'a4');
  const pageWidth = doc.internal.pageSize.getWidth();

  // Header
  doc.setFillColor(59, 130, 246);
  doc.rect(0, 0, pageWidth, 40, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(28);
  doc.setFont('helvetica', 'bold');
  doc.text('請求書', 20, 25);
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.text('INVOICE', 20, 33);

  // Invoice Number & Date
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(10);
  doc.text(`請求書番号: INV-${payment.id.slice(-8).toUpperCase()}`, pageWidth - 70, 55);
  doc.text(`発行日: ${payment.createdAt.toLocaleDateString('ja-JP')}`, pageWidth - 70, 62);

  // Gym Info
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('発行元', 20, 55);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.text(gymInfo.name || 'GYM MATCH Manager', 20, 62);
  if (gymInfo.address) doc.text(gymInfo.address, 20, 69);
  if (gymInfo.phone) doc.text(`TEL: ${gymInfo.phone}`, 20, 76);

  // Customer Info
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('請求先', 20, 95);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.text(`${payment.memberName} 様`, 20, 102);

  // Items Table
  const tableStartY = 120;
  doc.setFillColor(59, 130, 246);
  doc.rect(20, tableStartY, pageWidth - 40, 10, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.text('品目', 25, tableStartY + 7);
  doc.text('数量', pageWidth - 90, tableStartY + 7);
  doc.text('単価', pageWidth - 70, tableStartY + 7);
  doc.text('金額', pageWidth - 40, tableStartY + 7, { align: 'right' });

  // Item Row
  doc.setTextColor(0, 0, 0);
  doc.setFont('helvetica', 'normal');
  const typeLabels: any = {
    session: 'トレーニングセッション',
    membership: '月額会費',
    product: '商品',
    other: 'その他',
  };
  doc.text(payment.description || typeLabels[payment.type] || 'サービス', 25, tableStartY + 17);
  doc.text('1', pageWidth - 90, tableStartY + 17);
  doc.text(`¥${payment.amount.toLocaleString()}`, pageWidth - 70, tableStartY + 17);
  doc.text(`¥${payment.amount.toLocaleString()}`, pageWidth - 25, tableStartY + 17, { align: 'right' });

  // Line
  doc.setDrawColor(200, 200, 200);
  doc.line(20, tableStartY + 20, pageWidth - 20, tableStartY + 20);

  // Subtotal, Tax, Total
  const summaryY = tableStartY + 30;
  doc.setFont('helvetica', 'bold');
  doc.text('小計', pageWidth - 80, summaryY);
  doc.text(`¥${payment.amount.toLocaleString()}`, pageWidth - 25, summaryY, { align: 'right' });

  const tax = Math.round(payment.amount * 0.1); // 10% tax
  doc.setFont('helvetica', 'normal');
  doc.text('消費税 (10%)', pageWidth - 80, summaryY + 7);
  doc.text(`¥${tax.toLocaleString()}`, pageWidth - 25, summaryY + 7, { align: 'right' });

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.text('合計金額', pageWidth - 80, summaryY + 17);
  doc.text(`¥${(payment.amount + tax).toLocaleString()}`, pageWidth - 25, summaryY + 17, { align: 'right' });

  // Notes
  if (payment.metadata?.notes) {
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text('備考', 20, summaryY + 30);
    doc.text(payment.metadata.notes, 20, summaryY + 37);
  }

  // Footer
  doc.setTextColor(128, 128, 128);
  doc.setFontSize(8);
  doc.text(
    `Generated by GYM MATCH Manager - ${new Date().toLocaleString('ja-JP')}`,
    pageWidth / 2,
    280,
    { align: 'center' }
  );

  const pdfBlob = doc.output('blob');
  if (filename) {
    doc.save(filename);
  }
  return pdfBlob;
}

/**
 * Generate invoice from invoice data (more flexible)
 */
export async function generateCustomInvoicePDF(data: InvoiceData, filename?: string): Promise<Blob> {
  const doc = new jsPDF('p', 'mm', 'a4');
  const pageWidth = doc.internal.pageSize.getWidth();

  // Header
  doc.setFillColor(59, 130, 246);
  doc.rect(0, 0, pageWidth, 40, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(28);
  doc.setFont('helvetica', 'bold');
  doc.text('請求書', 20, 25);

  // Invoice details
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(10);
  doc.text(`請求書番号: ${data.invoiceNumber}`, pageWidth - 70, 55);
  doc.text(`発行日: ${data.issueDate.toLocaleDateString('ja-JP')}`, pageWidth - 70, 62);
  doc.text(`支払期限: ${data.dueDate.toLocaleDateString('ja-JP')}`, pageWidth - 70, 69);

  // Gym info
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('発行元', 20, 55);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.text(data.gymName, 20, 62);
  if (data.gymAddress) doc.text(data.gymAddress, 20, 69);
  if (data.gymPhone) doc.text(`TEL: ${data.gymPhone}`, 20, 76);

  // Customer info
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('請求先', 20, 95);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.text(`${data.customerName} 様`, 20, 102);
  if (data.customerEmail) doc.text(data.customerEmail, 20, 109);

  // Items table
  const tableStartY = 125;
  doc.setFillColor(59, 130, 246);
  doc.rect(20, tableStartY, pageWidth - 40, 10, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.text('品目', 25, tableStartY + 7);
  doc.text('数量', pageWidth - 90, tableStartY + 7);
  doc.text('単価', pageWidth - 60, tableStartY + 7);
  doc.text('金額', pageWidth - 25, tableStartY + 7, { align: 'right' });

  // Items
  doc.setTextColor(0, 0, 0);
  doc.setFont('helvetica', 'normal');
  let currentY = tableStartY + 17;
  data.items.forEach(item => {
    doc.text(item.description, 25, currentY);
    doc.text(item.quantity.toString(), pageWidth - 90, currentY);
    doc.text(`¥${item.unitPrice.toLocaleString()}`, pageWidth - 60, currentY);
    doc.text(`¥${item.amount.toLocaleString()}`, pageWidth - 25, currentY, { align: 'right' });
    currentY += 7;
  });

  doc.setDrawColor(200, 200, 200);
  doc.line(20, currentY, pageWidth - 20, currentY);

  // Summary
  currentY += 10;
  doc.setFont('helvetica', 'bold');
  doc.text('小計', pageWidth - 80, currentY);
  doc.text(`¥${data.subtotal.toLocaleString()}`, pageWidth - 25, currentY, { align: 'right' });

  currentY += 7;
  doc.setFont('helvetica', 'normal');
  doc.text('消費税', pageWidth - 80, currentY);
  doc.text(`¥${data.tax.toLocaleString()}`, pageWidth - 25, currentY, { align: 'right' });

  currentY += 10;
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.text('合計金額', pageWidth - 80, currentY);
  doc.text(`¥${data.total.toLocaleString()}`, pageWidth - 25, currentY, { align: 'right' });

  // Notes
  if (data.notes) {
    currentY += 15;
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text('備考', 20, currentY);
    doc.text(data.notes, 20, currentY + 7);
  }

  // Footer
  doc.setTextColor(128, 128, 128);
  doc.setFontSize(8);
  doc.text(
    `Generated by GYM MATCH Manager`,
    pageWidth / 2,
    280,
    { align: 'center' }
  );

  const pdfBlob = doc.output('blob');
  if (filename) {
    doc.save(filename);
  }
  return pdfBlob;
}
