/**
 * PDF Generator for GYM MATCH Manager Reports
 * 
 * Features:
 * - Monthly revenue reports with charts
 * - Session summaries with trainer breakdown
 * - Professional formatting with company branding
 * - Automatic page breaks and headers/footers
 */

import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

// Report data interfaces
export interface MonthlyReportData {
  gymName: string;
  reportMonth: string; // Format: "YYYY-MM"
  totalRevenue: number;
  totalSessions: number;
  memberCount: number;
  trainerCount: number;
  sessionBreakdown: {
    personal: { count: number; revenue: number };
    group: { count: number; revenue: number };
    trial: { count: number; revenue: number };
  };
  trainerBreakdown: Array<{
    trainerName: string;
    sessions: number;
    revenue: number;
    compensation: number;
  }>;
  dailyRevenue: Array<{
    date: string;
    revenue: number;
    sessions: number;
  }>;
}

export interface SessionReportData {
  gymName: string;
  startDate: string;
  endDate: string;
  sessions: Array<{
    id: string;
    date: string;
    memberName: string;
    trainerName: string;
    type: string;
    price: number;
    status: string;
  }>;
  totalRevenue: number;
}

/**
 * Generate Monthly Revenue Report PDF
 */
export async function generateMonthlyReportPDF(
  data: MonthlyReportData,
  filename?: string
): Promise<Blob> {
  const doc = new jsPDF('p', 'mm', 'a4');
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;

  // Helper function to add header
  const addHeader = (pageNumber: number) => {
    doc.setFillColor(59, 130, 246); // Blue
    doc.rect(0, 0, pageWidth, 40, 'F');
    
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(24);
    doc.setFont('helvetica', 'bold');
    doc.text('GYM MATCH Manager', margin, 20);
    
    doc.setFontSize(12);
    doc.setFont('helvetica', 'normal');
    doc.text('月次売上レポート', margin, 30);
    
    // Page number
    doc.setFontSize(10);
    doc.text(`Page ${pageNumber}`, pageWidth - margin - 20, 30);
  };

  // Helper function to add footer
  const addFooter = (pageNumber: number) => {
    doc.setTextColor(128, 128, 128);
    doc.setFontSize(8);
    doc.text(
      `Generated by GYM MATCH Manager - ${new Date().toLocaleString('ja-JP')}`,
      pageWidth / 2,
      pageHeight - 10,
      { align: 'center' }
    );
  };

  // Page 1: Summary
  let currentPage = 1;
  addHeader(currentPage);

  // Gym name and report period
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text(data.gymName, margin, 55);

  doc.setFontSize(14);
  doc.setFont('helvetica', 'normal');
  const reportDate = new Date(data.reportMonth + '-01');
  doc.text(
    `${reportDate.getFullYear()}年${reportDate.getMonth() + 1}月度`,
    margin,
    65
  );

  // Summary metrics
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('📊 サマリー', margin, 80);

  // Summary boxes
  const boxWidth = (pageWidth - 2 * margin - 10) / 2;
  const boxHeight = 25;
  let yPos = 90;

  // Total Revenue
  doc.setFillColor(239, 246, 255);
  doc.roundedRect(margin, yPos, boxWidth, boxHeight, 3, 3, 'F');
  doc.setTextColor(59, 130, 246);
  doc.setFontSize(10);
  doc.text('総売上', margin + 5, yPos + 8);
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text(
    `¥${data.totalRevenue.toLocaleString()}`,
    margin + 5,
    yPos + 20
  );

  // Total Sessions
  doc.setFillColor(243, 244, 246);
  doc.roundedRect(margin + boxWidth + 10, yPos, boxWidth, boxHeight, 3, 3, 'F');
  doc.setTextColor(75, 85, 99);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text('総セッション数', margin + boxWidth + 15, yPos + 8);
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text(
    `${data.totalSessions}回`,
    margin + boxWidth + 15,
    yPos + 20
  );

  yPos += boxHeight + 10;

  // Member Count
  doc.setFillColor(239, 246, 255);
  doc.roundedRect(margin, yPos, boxWidth, boxHeight, 3, 3, 'F');
  doc.setTextColor(59, 130, 246);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text('会員数', margin + 5, yPos + 8);
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text(`${data.memberCount}名`, margin + 5, yPos + 20);

  // Trainer Count
  doc.setFillColor(243, 244, 246);
  doc.roundedRect(margin + boxWidth + 10, yPos, boxWidth, boxHeight, 3, 3, 'F');
  doc.setTextColor(75, 85, 99);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text('トレーナー数', margin + boxWidth + 15, yPos + 8);
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text(`${data.trainerCount}名`, margin + boxWidth + 15, yPos + 20);

  // Session Type Breakdown
  yPos += boxHeight + 20;
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(0, 0, 0);
  doc.text('📋 セッションタイプ別内訳', margin, yPos);

  yPos += 10;
  const tableData = [
    ['タイプ', 'セッション数', '売上'],
    [
      'パーソナル',
      `${data.sessionBreakdown.personal.count}回`,
      `¥${data.sessionBreakdown.personal.revenue.toLocaleString()}`,
    ],
    [
      'グループ',
      `${data.sessionBreakdown.group.count}回`,
      `¥${data.sessionBreakdown.group.revenue.toLocaleString()}`,
    ],
    [
      '体験',
      `${data.sessionBreakdown.trial.count}回`,
      `¥${data.sessionBreakdown.trial.revenue.toLocaleString()}`,
    ],
  ];

  // Draw table
  const colWidths = [60, 50, 60];
  const rowHeight = 10;
  
  tableData.forEach((row, rowIndex) => {
    let xPos = margin;
    
    if (rowIndex === 0) {
      // Header row
      doc.setFillColor(59, 130, 246);
      doc.rect(margin, yPos, colWidths.reduce((a, b) => a + b, 0), rowHeight, 'F');
      doc.setTextColor(255, 255, 255);
      doc.setFont('helvetica', 'bold');
    } else {
      // Data rows
      doc.setFillColor(rowIndex % 2 === 0 ? 249, 250, 251 : 255, 255, 255);
      doc.rect(margin, yPos, colWidths.reduce((a, b) => a + b, 0), rowHeight, 'F');
      doc.setTextColor(0, 0, 0);
      doc.setFont('helvetica', 'normal');
    }
    
    doc.setFontSize(10);
    row.forEach((cell, colIndex) => {
      doc.text(cell, xPos + 5, yPos + 7);
      xPos += colWidths[colIndex];
    });
    
    yPos += rowHeight;
  });

  // Trainer Breakdown
  yPos += 15;
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(0, 0, 0);
  doc.text('👤 トレーナー別実績', margin, yPos);

  yPos += 10;
  const trainerTableData = [
    ['トレーナー', 'セッション', '売上', '報酬'],
    ...data.trainerBreakdown.map((trainer) => [
      trainer.trainerName,
      `${trainer.sessions}回`,
      `¥${trainer.revenue.toLocaleString()}`,
      `¥${trainer.compensation.toLocaleString()}`,
    ]),
  ];

  const trainerColWidths = [50, 35, 40, 40];
  
  trainerTableData.forEach((row, rowIndex) => {
    // Check if we need a new page
    if (yPos > pageHeight - 50) {
      addFooter(currentPage);
      doc.addPage();
      currentPage++;
      addHeader(currentPage);
      yPos = 60;
    }
    
    let xPos = margin;
    
    if (rowIndex === 0) {
      doc.setFillColor(59, 130, 246);
      doc.rect(margin, yPos, trainerColWidths.reduce((a, b) => a + b, 0), rowHeight, 'F');
      doc.setTextColor(255, 255, 255);
      doc.setFont('helvetica', 'bold');
    } else {
      doc.setFillColor(rowIndex % 2 === 0 ? 249, 250, 251 : 255, 255, 255);
      doc.rect(margin, yPos, trainerColWidths.reduce((a, b) => a + b, 0), rowHeight, 'F');
      doc.setTextColor(0, 0, 0);
      doc.setFont('helvetica', 'normal');
    }
    
    doc.setFontSize(9);
    row.forEach((cell, colIndex) => {
      doc.text(cell, xPos + 3, yPos + 7);
      xPos += trainerColWidths[colIndex];
    });
    
    yPos += rowHeight;
  });

  addFooter(currentPage);

  // Save PDF
  const pdfBlob = doc.output('blob');
  
  if (filename) {
    doc.save(filename);
  }
  
  return pdfBlob;
}

/**
 * Generate Session List Report PDF
 */
export async function generateSessionReportPDF(
  data: SessionReportData,
  filename?: string
): Promise<Blob> {
  const doc = new jsPDF('p', 'mm', 'a4');
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;

  let currentPage = 1;

  // Header
  doc.setFillColor(59, 130, 246);
  doc.rect(0, 0, pageWidth, 40, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text('GYM MATCH Manager', margin, 20);
  
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.text('セッション一覧レポート', margin, 30);

  // Report period
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text(data.gymName, margin, 55);
  
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.text(`期間: ${data.startDate} 〜 ${data.endDate}`, margin, 65);

  // Total revenue
  doc.setFontSize(10);
  doc.text(`総売上: ¥${data.totalRevenue.toLocaleString()}`, margin, 75);

  // Sessions table
  let yPos = 90;
  const tableHeaders = ['日付', '会員', 'トレーナー', 'タイプ', '金額'];
  const colWidths = [25, 35, 35, 30, 30];
  const rowHeight = 8;

  // Draw table header
  doc.setFillColor(59, 130, 246);
  doc.rect(margin, yPos, colWidths.reduce((a, b) => a + b, 0), rowHeight, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);

  let xPos = margin;
  tableHeaders.forEach((header, index) => {
    doc.text(header, xPos + 2, yPos + 6);
    xPos += colWidths[index];
  });

  yPos += rowHeight;

  // Draw table rows
  data.sessions.forEach((session, index) => {
    // Check if we need a new page
    if (yPos > pageHeight - 30) {
      doc.setTextColor(128, 128, 128);
      doc.setFontSize(8);
      doc.text(
        `Page ${currentPage} - Generated by GYM MATCH Manager`,
        pageWidth / 2,
        pageHeight - 10,
        { align: 'center' }
      );
      
      doc.addPage();
      currentPage++;
      yPos = 20;
      
      // Redraw header on new page
      doc.setFillColor(59, 130, 246);
      doc.rect(margin, yPos, colWidths.reduce((a, b) => a + b, 0), rowHeight, 'F');
      doc.setTextColor(255, 255, 255);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(9);

      xPos = margin;
      tableHeaders.forEach((header, index) => {
        doc.text(header, xPos + 2, yPos + 6);
        xPos += colWidths[index];
      });

      yPos += rowHeight;
    }

    // Row background
    doc.setFillColor(index % 2 === 0 ? 249, 250, 251 : 255, 255, 255);
    doc.rect(margin, yPos, colWidths.reduce((a, b) => a + b, 0), rowHeight, 'F');

    // Row data
    doc.setTextColor(0, 0, 0);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);

    const rowData = [
      new Date(session.date).toLocaleDateString('ja-JP', { month: '2-digit', day: '2-digit' }),
      session.memberName,
      session.trainerName,
      session.type,
      `¥${session.price.toLocaleString()}`,
    ];

    xPos = margin;
    rowData.forEach((data, colIndex) => {
      doc.text(data, xPos + 2, yPos + 6);
      xPos += colWidths[colIndex];
    });

    yPos += rowHeight;
  });

  // Footer
  doc.setTextColor(128, 128, 128);
  doc.setFontSize(8);
  doc.text(
    `Page ${currentPage} - Generated by GYM MATCH Manager - ${new Date().toLocaleString('ja-JP')}`,
    pageWidth / 2,
    pageHeight - 10,
    { align: 'center' }
  );

  // Save PDF
  const pdfBlob = doc.output('blob');
  
  if (filename) {
    doc.save(filename);
  }
  
  return pdfBlob;
}

/**
 * Convert HTML element to PDF (for charts and complex layouts)
 */
export async function htmlToPDF(
  elementId: string,
  filename: string,
  options?: {
    orientation?: 'portrait' | 'landscape';
    title?: string;
  }
): Promise<Blob> {
  const element = document.getElementById(elementId);
  
  if (!element) {
    throw new Error(`Element with id "${elementId}" not found`);
  }

  // Capture element as canvas
  const canvas = await html2canvas(element, {
    scale: 2,
    useCORS: true,
    logging: false,
  });

  const imgData = canvas.toDataURL('image/png');
  const imgWidth = canvas.width;
  const imgHeight = canvas.height;

  // Create PDF
  const orientation = options?.orientation || 'portrait';
  const doc = new jsPDF(orientation, 'mm', 'a4');
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  // Calculate dimensions to fit page
  const ratio = Math.min(
    (pageWidth - 20) / imgWidth,
    (pageHeight - 40) / imgHeight
  );
  
  const width = imgWidth * ratio;
  const height = imgHeight * ratio;
  const x = (pageWidth - width) / 2;
  const y = 30;

  // Add title if provided
  if (options?.title) {
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.text(options.title, pageWidth / 2, 15, { align: 'center' });
  }

  // Add image
  doc.addImage(imgData, 'PNG', x, y, width, height);

  // Footer
  doc.setTextColor(128, 128, 128);
  doc.setFontSize(8);
  doc.text(
    `Generated by GYM MATCH Manager - ${new Date().toLocaleString('ja-JP')}`,
    pageWidth / 2,
    pageHeight - 10,
    { align: 'center' }
  );

  const pdfBlob = doc.output('blob');
  doc.save(filename);
  
  return pdfBlob;
}

/**
 * Download blob as file
 */
export function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
